# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 2
  seed: 1337
  tensorboard_logdir: tblog

checkpoint:
  save_interval_updates: 25000
  keep_interval_updates: 2
  no_epoch_checkpoints: true
 
distributed_training:
  ddp_backend: no_c10d
  distributed_world_size: 1
  nprocs_per_node: 1
  find_unused_parameters: true

task:
  _name: hubert_pretraining
  data: /home/alisafaya/shallow.ai/workspace_asr_alhubert/bin
  label_dir: /home/alisafaya/shallow.ai/workspace_asr_alhubert/bin
  labels: ["km"]
  label_rate: 50
  sample_rate: 16000
  max_sample_size: 260000
  min_sample_size: 32000
  pad_audio: false
  random_crop: true
  normalize: true # must be consistent with extractor

dataset:
  num_workers: 2
  max_tokens: 300000
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 5
  validate_interval_updates: 5000

criterion:
  _name: hubert
  pred_masked_weight: 1.0
  pred_nomask_weight: 0.0
  loss_weights: [10,]

optimization:
  max_update: 600000
  lr: [0.001,]
  clip_norm: 1.0
  update_freq: [2]

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler:
  _name: polynomial_decay
  warmup_updates: 5000

model:
  _name: hubert
  label_rate: 50
  skip_masked: false
  skip_nomask: false
  extractor_mode: layer_norm
  conv_feature_layers: '[(32,10,5),(64,3,4),(128,3,2),(256,3,2),(512,3,2),(512,2,2),(512,2,2)]'
  mask_prob: 0.80
# BASE
  encoder_ffn_embed_dim: 1536
  encoder_embed_dim: 768
  encoder_layers: 16
  encoder_attention_heads: 8
# SMALL
  # encoder_ffn_embed_dim: 1024
  # encoder_embed_dim: 512
  # encoder_layers: 8
  # encoder_attention_heads: 8

  encoder_layerdrop: 0.1
  final_dim: 512
  dropout_input: 0.0
  dropout_features: 0.0
  dropout: 0.0
  attention_dropout: 0.0
  feature_grad_mult: 1.0
  activation_dropout: 0.0
  layer_norm_first: true
  untie_final_proj: true
  encoder_shared_layers: true
  activation_fn: gated_relu
  use_rmsnorm: true
  ffn_bias: false

hydra:
  job:
    config:
      override_dirname:
        kv_sep: '-'
        item_sep: '__'
        exclude_keys:
          - run
          - task.data
  run:
    dir: /home/alisafaya/shallow.ai/workspace_asr_alhubert/bin/alhubert_base/
  sweep:
    dir: /home/alisafaya/shallow.ai/workspace_asr_alhubert/bin/alhubert_base/
    subdir: ${hydra.job.config_name}__${hydra.job.override_dirname}